// Generated by scripts/prepare-ramp.mjs — do not edit
export type RampSectionMeta = {
  slug: string;
  file: string;
  title: string;
};

export const RAMP_SECTION_MANIFEST: RampSectionMeta[] = [
  {
    "slug": "logos-marquee",
    "file": "01-logos-marquee.html",
    "title": "Join 70,000 of the world’s most ambitious companies growing 3.2x faster than the average American bu"
  },
  {
    "slug": "platform-back-office",
    "file": "02-platform-back-office.html",
    "title": "One platform for your entire back office. Infinite agents that work 24/7."
  },
  {
    "slug": "systems-integration",
    "file": "03-systems-integration.html",
    "title": "Systems that never spoke"
  },
  {
    "slug": "finance-intelligence",
    "file": "04-finance-intelligence.html",
    "title": "Built on the intelligence of 70k+ finance teams. One platform for the agentic era."
  },
  {
    "slug": "stack-banner",
    "file": "05-stack-banner.html",
    "title": "Section 5"
  },
  {
    "slug": "team-scale",
    "file": "06-team-scale.html",
    "title": "Scale the team.Shrink the paperwork."
  },
  {
    "slug": "testimonials",
    "file": "07-testimonials.html",
    "title": "We've got the receipts."
  }
];

export const RAMP_STYLESHEETS: string[] = [
  "/ramp-files/0g8gib8b5vkql.css",
  "/ramp-files/0u4q_26oq7xb..css",
  "/ramp-files/0o6-x3tyjckd..css",
  "/ramp-files/08b.4-de09mkh.css",
  "/ramp-files/12r3gowaga-ug.css"
];
