export type Country = { code: string; label: string; flag: string };

export const countries: Country[] = [
  { code: "GB", label: "United Kingdom", flag: "🇬🇧" },
  { code: "IE", label: "Ireland", flag: "🇮🇪" },
  { code: "US", label: "United States", flag: "🇺🇸" },
  { code: "CA", label: "Canada", flag: "🇨🇦" },
  { code: "AU", label: "Australia", flag: "🇦🇺" },
  { code: "DE", label: "Germany", flag: "🇩🇪" },
  { code: "FR", label: "France", flag: "🇫🇷" },
  { code: "NL", label: "Netherlands", flag: "🇳🇱" },
  { code: "ES", label: "Spain", flag: "🇪🇸" },
  { code: "IT", label: "Italy", flag: "🇮🇹" },
  { code: "PT", label: "Portugal", flag: "🇵🇹" },
  { code: "BE", label: "Belgium", flag: "🇧🇪" },
  { code: "AT", label: "Austria", flag: "🇦🇹" },
  { code: "CH", label: "Switzerland", flag: "🇨🇭" },
  { code: "SE", label: "Sweden", flag: "🇸🇪" },
  { code: "NO", label: "Norway", flag: "🇳🇴" },
  { code: "DK", label: "Denmark", flag: "🇩🇰" },
  { code: "FI", label: "Finland", flag: "🇫🇮" },
  { code: "PL", label: "Poland", flag: "🇵🇱" },
  { code: "LU", label: "Luxembourg", flag: "🇱🇺" },
  { code: "AL", label: "Albania", flag: "🇦🇱" },
  { code: "AD", label: "Andorra", flag: "🇦🇩" },
  { code: "BY", label: "Belarus", flag: "🇧🇾" },
  { code: "BA", label: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "BG", label: "Bulgaria", flag: "🇧🇬" },
  { code: "HR", label: "Croatia", flag: "🇭🇷" },
  { code: "CY", label: "Cyprus", flag: "🇨🇾" },
  { code: "CZ", label: "Czechia", flag: "🇨🇿" },
  { code: "EE", label: "Estonia", flag: "🇪🇪" },
  { code: "GR", label: "Greece", flag: "🇬🇷" },
  { code: "HU", label: "Hungary", flag: "🇭🇺" },
  { code: "IS", label: "Iceland", flag: "🇮🇸" },
  { code: "XK", label: "Kosovo", flag: "🇽🇰" },
  { code: "LV", label: "Latvia", flag: "🇱🇻" },
  { code: "LI", label: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", label: "Lithuania", flag: "🇱🇹" },
  { code: "MT", label: "Malta", flag: "🇲🇹" },
  { code: "MD", label: "Moldova", flag: "🇲🇩" },
  { code: "MC", label: "Monaco", flag: "🇲🇨" },
  { code: "ME", label: "Montenegro", flag: "🇲🇪" },
  { code: "MK", label: "North Macedonia", flag: "🇲🇰" },
  { code: "RO", label: "Romania", flag: "🇷🇴" },
  { code: "SM", label: "San Marino", flag: "🇸🇲" },
  { code: "RS", label: "Serbia", flag: "🇷🇸" },
  { code: "SK", label: "Slovakia", flag: "🇸🇰" },
  { code: "SI", label: "Slovenia", flag: "🇸🇮" },
  { code: "UA", label: "Ukraine", flag: "🇺🇦" },
  { code: "VA", label: "Vatican City", flag: "🇻🇦" },
  { code: "NZ", label: "New Zealand", flag: "🇳🇿" },
  { code: "SG", label: "Singapore", flag: "🇸🇬" },
];
