import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

function stripContainerByClass(html, partialClass) {
  let result = html;
  let searchFrom = 0;
  while (searchFrom < result.length) {
    const classIdx = result.indexOf(partialClass, searchFrom);
    if (classIdx === -1) break;
    const start = result.lastIndexOf("<div", classIdx);
    if (start === -1) break;
    let depth = 0;
    let i = start;
    let end = -1;
    while (i < result.length) {
      if (result.startsWith("<div", i)) depth++;
      else if (result.startsWith("</div>", i)) {
        depth--;
        if (depth === 0) {
          end = i + 6;
          break;
        }
      }
      i++;
    }
    if (end === -1) break;
    result = result.slice(0, start) + result.slice(end);
    searchFrom = start;
  }
  return result;
}

function stripElementByFramerName(html, framerName) {
  const needle = `data-framer-name="${framerName}"`;
  let result = html;
  let searchFrom = 0;
  while (searchFrom < result.length) {
    const nameIdx = result.indexOf(needle, searchFrom);
    if (nameIdx === -1) break;
    const start = result.lastIndexOf("<div", nameIdx);
    if (start === -1) break;
    let depth = 0;
    let i = start;
    let end = -1;
    while (i < result.length) {
      if (result.startsWith("<div", i)) depth++;
      else if (result.startsWith("</div>", i)) {
        depth--;
        if (depth === 0) {
          end = i + 6;
          break;
        }
      }
      i++;
    }
    if (end === -1) break;
    result = result.slice(0, start) + result.slice(end);
    searchFrom = start;
  }
  return result;
}

function stripReactReplacedSections(html) {
  const containers = [
    "framer-16bgs19-container", // scroll / demo hero
    "framer-623ofv-container", // fixed nav
    "framer-14hkwql-container", // footer
  ];
  let out = html;
  for (const cls of containers) {
    const before = out.length;
    out = stripContainerByClass(out, cls);
    if (before !== out.length) console.log(`  stripped ${cls} (${before - out.length} bytes)`);
  }
  for (const name of ["hero-s"]) {
    const before = out.length;
    out = stripElementByFramerName(out, name);
    if (before !== out.length) console.log(`  stripped [${name}] (${before - out.length} bytes)`);
  }
  return out;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const sourceHtml = join(root, "BOND.html");
const outputHtml = join(root, "public", "bond.html");
const sourceAssets = join(root, "BOND_files");
const publicAssets = join(root, "public", "BOND_files");
const customDir = join(root, "custom");
const publicCustomDir = join(root, "public", "custom");

const MAIN_CLOSE = "</div><!--/$--></div>";

const CUSTOM_TAGS = `
<link rel="stylesheet" href="/custom/overrides.css" />
<script src="/custom/overrides.js"></script>
`;

function extractFramerCss(html) {
  const parts = [];
  const patterns = [
    /<style data-framer-font-css="">([\s\S]*?)<\/style>/,
    /<style data-framer-css-ssr-minified=""[^>]*>([\s\S]*?)<\/style>/,
    /<style data-framer-html-style="">([\s\S]*?)<\/style>/,
  ];
  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match) parts.push(match[1]);
  }
  return parts.join("\n\n");
}

function extractMainInner(html) {
  const mainStart = html.indexOf('<div id="main"');
  if (mainStart === -1) return "";
  const mainOpenEnd = html.indexOf(">", mainStart) + 1;
  const lastClose = html.lastIndexOf(MAIN_CLOSE);
  if (lastClose === -1) return "";
  return html.slice(mainOpenEnd, lastClose);
}

/** Cut Framer overlay + close unbalanced divs so injected HTML cannot swallow siblings. */
function sanitizeFramerBody(html) {
  let out = html;
  const overlay = out.indexOf('<div id="overlay">');
  if (overlay !== -1) out = out.slice(0, overlay);

  let depth = 0;
  const tagRe = /<\/?div\b[^>]*>/gi;
  let m;
  while ((m = tagRe.exec(out)) !== null) {
    if (m[0].startsWith("</")) depth--;
    else depth++;
  }

  if (depth > 0) out += "</div>".repeat(depth);
  else if (depth < 0) {
    console.warn(`framer-body had ${-depth} extra closing div(s); leaving as-is`);
  }

  return out.trim();
}

function writeFramerBodyModule(framerBody, root) {
  const outPath = join(root, "lib", "framer-body.generated.ts");
  const contents = `// Generated by scripts/prepare-html.mjs — do not edit\nexport const FRAMER_BODY_HTML = ${JSON.stringify(framerBody)};\n`;
  writeFileSync(outPath, contents, "utf-8");
}

if (!existsSync(sourceHtml)) {
  console.error("BOND.html not found at project root");
  process.exit(1);
}

mkdirSync(join(root, "public"), { recursive: true });
mkdirSync(join(root, "styles"), { recursive: true });

if (!existsSync(publicAssets)) {
  if (existsSync(sourceAssets)) {
    cpSync(sourceAssets, publicAssets, { recursive: true });
    console.log("Copied BOND_files to public/BOND_files");
  } else {
    console.error("BOND_files directory not found");
    process.exit(1);
  }
}

if (existsSync(customDir)) {
  mkdirSync(publicCustomDir, { recursive: true });
  for (const file of ["overrides.css", "overrides.js"]) {
    const src = join(customDir, file);
    if (existsSync(src)) {
      cpSync(src, join(publicCustomDir, file));
    }
  }
}

let html = readFileSync(sourceHtml, "utf-8");
html = html.replace(/\.\/BOND_files\//g, "/BOND_files/");

const sproutStart = html.indexOf('<div id="sprout-footer">');
if (sproutStart !== -1) {
  const overlayStart = html.indexOf('<div id="overlay">', sproutStart);
  if (overlayStart !== -1) {
    html = html.slice(0, sproutStart) + html.slice(overlayStart);
    console.log("Stripped embedded sprout-footer from BOND.html");
  }
}

// React app: middle sections only (hero/nav/footer stripped — React components own those)
const framerCss = extractFramerCss(html);
let framerBody = extractMainInner(html);
console.log("Stripping React-replaced Framer sections from body:");
framerBody = stripReactReplacedSections(framerBody);
framerBody = sanitizeFramerBody(framerBody);
writeFileSync(join(root, "public", "framer-styles.css"), framerCss, "utf-8");
writeFileSync(join(root, "styles", "framer-legacy.css"), framerCss, "utf-8");
writeFileSync(join(root, "public", "framer-body.html"), framerBody, "utf-8");
writeFramerBodyModule(framerBody, root);
console.log(
  `Extracted framer-styles.css (${framerCss.length} bytes) and framer-body.html (${framerBody.length} bytes)`
);

const footerPath = join(customDir, "footer.html");
const footerHtml = existsSync(footerPath)
  ? readFileSync(footerPath, "utf-8")
  : "";

const lastMainClose = html.lastIndexOf(MAIN_CLOSE);
if (lastMainClose !== -1 && footerHtml) {
  const afterMain = lastMainClose + MAIN_CLOSE.length;
  html = html.slice(0, afterMain) + footerHtml + html.slice(afterMain);
  console.log("Injected custom/footer.html after #main (legacy bond.html only)");
}

if (!html.includes("/custom/overrides.css")) {
  html = html.replace("</head>", `${CUSTOM_TAGS}</head>`);
}

writeFileSync(outputHtml, html, "utf-8");
console.log(`Prepared ${outputHtml} (${html.length} bytes)`);
console.log("Note: public/index.html is NOT generated — / is served by the Next.js app.");
