import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const RAMP_HTML = join(
  root,
  "Spend Management, Corporate Cards & Accounts Payable Solutions _ Ramp.html"
);
const RAMP_ASSETS_SRC = join(
  root,
  "Spend Management, Corporate Cards & Accounts Payable Solutions _ Ramp_files"
);
const RAMP_ASSETS_DST = join(root, "public", "ramp-files");
const RAMP_SECTIONS_DST = join(root, "public", "ramp-sections");
const MANIFEST_PATH = join(root, "lib", "ramp-sections.manifest.ts");

const ASSET_PATH_RAW =
  "./Spend Management, Corporate Cards & Accounts Payable Solutions _ Ramp_files/";
const ASSET_PATH_ENC =
  "./Spend Management, Corporate Cards &amp; Accounts Payable Solutions _ Ramp_files/";

/** Skip email capture modal; include all marketing sections */
const SECTION_SLUGS = [
  null, // 0 email
  "logos-marquee",
  "platform-back-office",
  "systems-integration",
  "finance-intelligence",
  "stack-banner",
  "team-scale",
  "testimonials",
];

function rewriteAssetPaths(html) {
  return html
    .replaceAll(ASSET_PATH_ENC, "/ramp-files/")
    .replaceAll(ASSET_PATH_RAW, "/ramp-files/");
}

function extractSections(html) {
  const sections = [];
  const re = /<section\b[^>]*>/gi;
  let match;
  const starts = [];
  while ((match = re.exec(html)) !== null) starts.push(match.index);

  for (let i = 0; i < starts.length; i++) {
    const start = starts[i];
    let depth = 0;
    let j = start;
    let end = -1;
    while (j < html.length) {
      if (html.startsWith("<section", j)) depth++;
      else if (html.startsWith("</section>", j)) {
        depth--;
        if (depth === 0) {
          end = j + 10;
          break;
        }
      }
      j++;
    }
    if (end === -1) continue;
    const chunk = html.slice(start, end);
    const h2Match = chunk.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
    const title = h2Match
      ? h2Match[1].replace(/<[^>]+>/g, "").trim().slice(0, 100)
      : `Section ${i}`;
    sections.push({ index: i, title, html: chunk });
  }
  return sections;
}

function extractRampCssLinks(html) {
  const links = [
    ...html.matchAll(
      /href="(\.\/Spend Management, Corporate Cards &(?:amp;)? Accounts Payable Solutions _ Ramp_files\/[^"]+\.css)"/gi
    ),
  ].map((m) => m[1].replace(/&amp;/g, "&"));
  return [...new Set(links)].map((p) =>
    p
      .replace(ASSET_PATH_ENC, "/ramp-files/")
      .replace(ASSET_PATH_RAW, "/ramp-files/")
  );
}

if (!existsSync(RAMP_HTML)) {
  if (existsSync(MANIFEST_PATH) && existsSync(RAMP_SECTIONS_DST)) {
    console.log("Ramp source removed — using committed public/ramp-sections");
    process.exit(0);
  }
  console.error("Ramp sections missing. Restore source HTML or public/ramp-sections/");
  process.exit(1);
}

mkdirSync(join(root, "public"), { recursive: true });
mkdirSync(RAMP_SECTIONS_DST, { recursive: true });

if (existsSync(RAMP_ASSETS_SRC) && !existsSync(RAMP_ASSETS_DST)) {
  cpSync(RAMP_ASSETS_SRC, RAMP_ASSETS_DST, { recursive: true });
  console.log("Copied Ramp assets to public/ramp-files");
} else if (existsSync(RAMP_ASSETS_SRC)) {
  // refresh missing files only — full sync on first copy
  console.log("public/ramp-files already exists");
}

const html = readFileSync(RAMP_HTML, "utf-8");
const sections = extractSections(html);
const cssLinks = extractRampCssLinks(html);

const manifest = [];

for (const section of sections) {
  const slug = SECTION_SLUGS[section.index];
  if (!slug) {
    console.log(`  skip section ${section.index} (${section.title.slice(0, 40)})`);
    continue;
  }

  const fileName = `${String(section.index).padStart(2, "0")}-${slug}.html`;
  const outPath = join(RAMP_SECTIONS_DST, fileName);
  const body = rewriteAssetPaths(section.html);
  writeFileSync(outPath, body, "utf-8");

  manifest.push({
    slug,
    file: fileName,
    title: section.title,
  });
  console.log(`  wrote ${fileName} (${body.length} bytes)`);
}

const manifestTs = `// Generated by scripts/prepare-ramp.mjs — do not edit
export type RampSectionMeta = {
  slug: string;
  file: string;
  title: string;
};

export const RAMP_SECTION_MANIFEST: RampSectionMeta[] = ${JSON.stringify(manifest, null, 2)};

export const RAMP_STYLESHEETS: string[] = ${JSON.stringify(cssLinks, null, 2)};
`;
writeFileSync(MANIFEST_PATH, manifestTs, "utf-8");
console.log(`Wrote manifest with ${manifest.length} sections`);
